SELECT DISTINCT 
    INFORMATION_SCHEMA.TABLES.TABLE_NAME                AS TABLE_NAME,
    INFORMATION_SCHEMA.TABLES.TABLE_TYPE                AS TABLE_TYPE,
    INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME              AS COLUMN_NAME, 
    INFORMATION_SCHEMA.COLUMNS.DATA_TYPE                AS DATA_TYPE, 
    INFORMATION_SCHEMA.COLUMNS.ORDINAL_POSITION         AS ORDINAL_POSITION, 
    INFORMATION_SCHEMA.COLUMNS.CHARACTER_MAXIMUM_LENGTH AS CHARACTER_MAXIMUM_LENGTH, 
    INFORMATION_SCHEMA.COLUMNS.NUMERIC_PRECISION        AS NUMERIC_PRECISION, 
    INFORMATION_SCHEMA.COLUMNS.NUMERIC_SCALE            AS NUMERIC_SCALE, 
    INFORMATION_SCHEMA.COLUMNS.IS_NULLABLE              AS IS_NULLABLE, 
    INFORMATION_SCHEMA.COLUMNS.IS_IDENTITY              AS IS_IDENTITY, 
    (SELECT INFORMATION_SCHEMA.TABLE_CONSTRAINTS.CONSTRAINT_TYPE 
     FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
     INNER JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE ON INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE.TABLE_NAME = INFORMATION_SCHEMA.TABLE_CONSTRAINTS.TABLE_NAME 
     AND INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE.CONSTRAINT_NAME = INFORMATION_SCHEMA.TABLE_CONSTRAINTS.CONSTRAINT_NAME 
     WHERE INFORMATION_SCHEMA.TABLE_CONSTRAINTS.TABLE_NAME = INFORMATION_SCHEMA.COLUMNS.TABLE_NAME 
     AND INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE.COLUMN_NAME = INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME LIMIT 1) 
                                                        AS CONSTRAINT_TYPE 
FROM 
    INFORMATION_SCHEMA.TABLES 
LEFT JOIN 
    INFORMATION_SCHEMA.COLUMNS ON INFORMATION_SCHEMA.COLUMNS.TABLE_NAME = INFORMATION_SCHEMA.TABLES.TABLE_NAME 
LEFT JOIN 
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE ON INFORMATION_SCHEMA.KEY_COLUMN_USAGE.TABLE_NAME = INFORMATION_SCHEMA.COLUMNS.TABLE_NAME 
    AND 
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE.COLUMN_NAME = INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME 
WHERE 
    INFORMATION_SCHEMA.TABLES.TABLE_SCHEMA <> 'pg_catalog' AND INFORMATION_SCHEMA.TABLES.TABLE_SCHEMA <> 'information_schema' 
ORDER BY 
    INFORMATION_SCHEMA.TABLES.TABLE_NAME, 
    INFORMATION_SCHEMA.COLUMNS.ORDINAL_POSITION
