SELECT
    RDB$RELATION_NAME       AS TABLE_NAME,
    CASE WHEN RDB$VIEW_BLR IS NULL
        THEN 'BASE TABLE'
        ELSE 'VIEW'
    END                     AS TABLE_TYPE
FROM
    RDB$RELATIONS
WHERE
    RDB$SYSTEM_FLAG = 0
ORDER BY
    RDB$RELATION_NAME
