SELECT
  USER_TABLES.TABLE_NAME,
  'BASE TABLE'                    AS TABLE_TYPE
FROM
  USER_TABLES

UNION ALL

SELECT
  USER_VIEWS.VIEW_NAME            AS TABLE_NAME,
  'VIEW'                          AS TABLE_TYPE
FROM
  USER_VIEWS
ORDER BY
  TABLE_NAME
