SELECT
  DECODE(USER_PROCEDURES.procedure_name, NULL, 
         USER_PROCEDURES.object_name || USER_PROCEDURES.procedure_name, 
         USER_PROCEDURES.procedure_name)        AS ROUTINE_NAME, 
  USER_OBJECTS.OBJECT_TYPE                      AS ROUTINE_TYPE,
  USER_ARGUMENTS.ARGUMENT_NAME                  AS PARAMETER_NAME,
  USER_ARGUMENTS.IN_OUT                         AS PARAMETER_MODE,
  USER_ARGUMENTS.DATA_TYPE                      AS DATA_TYPE,
  USER_ARGUMENTS.POSITION                       AS ORDINAL_POSITION,
  USER_ARGUMENTS.DATA_LENGTH                    AS CHARACTER_MAXIMUM_LENGTH,
  USER_ARGUMENTS.DATA_PRECISION                 AS NUMERIC_PRECISION,
  USER_ARGUMENTS.DATA_SCALE                     AS NUMERIC_SCALE
FROM
  USER_PROCEDURES
INNER JOIN
  USER_OBJECTS ON USER_OBJECTS.OBJECT_NAME = USER_PROCEDURES.OBJECT_NAME
LEFT JOIN
  USER_ARGUMENTS ON USER_ARGUMENTS.OBJECT_NAME = USER_PROCEDURES.OBJECT_NAME
WHERE
  USER_OBJECTS.OBJECT_TYPE IN ('PROCEDURE', 'FUNCTION')
ORDER BY
  USER_PROCEDURES.OBJECT_NAME,
  USER_ARGUMENTS.POSITION
