SELECT 
    INFORMATION_SCHEMA.TABLES.TABLE_NAME, 
    INFORMATION_SCHEMA.TABLES.TABLE_TYPE 
FROM 
    INFORMATION_SCHEMA.TABLES 
WHERE 
    INFORMATION_SCHEMA.TABLES.TABLE_NAME <> 'sysdiagrams' 
AND 
    INFORMATION_SCHEMA.TABLES.TABLE_NAME <> 'sysmessages' 
AND 
    INFORMATION_SCHEMA.TABLES.TABLE_NAME <> 'sysobjects' 
ORDER BY 
    INFORMATION_SCHEMA.TABLES.TABLE_NAME
