SELECT 
    INFORMATION_SCHEMA.COLUMNS.ORDINAL_POSITION, 
    INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME, 
    INFORMATION_SCHEMA.COLUMNS.DATA_TYPE, 
    INFORMATION_SCHEMA.COLUMNS.CHARACTER_MAXIMUM_LENGTH, 
    INFORMATION_SCHEMA.COLUMNS.NUMERIC_PRECISION, 
    INFORMATION_SCHEMA.COLUMNS.NUMERIC_SCALE, 
    INFORMATION_SCHEMA.COLUMNS.IS_NULLABLE, 
    CASE WHEN 
		ISNULL(ColumnProperty(Object_ID(QuoteName(KEY_COLUMN_USAGE.TABLE_SCHEMA) + '.' + QuoteName(KEY_COLUMN_USAGE.TABLE_NAME)), 
												  KEY_COLUMN_USAGE.COLUMN_NAME, 'IsIdentity'), 0) = 1 THEN 
		1
	ELSE 
		(SELECT TOP 1 
			C.IS_IDENTITY 
		 FROM 
			SYS.OBJECTS O 
		 INNER JOIN 
			SYS.COLUMNS C ON O.OBJECT_ID = C.OBJECT_ID 
		 WHERE 
			O.TYPE = 'U' 
		 AND 
			O.NAME = INFORMATION_SCHEMA.COLUMNS.TABLE_NAME
		AND
			C.NAME = INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME)
	END  AS IS_IDENTITY, 
                                                        
    CASE WHEN SYS.IDENTITY_COLUMNS.NAME IS NULL THEN
		ISNULL(ColumnProperty(Object_ID(QuoteName(KEY_COLUMN_USAGE.TABLE_SCHEMA) + '.' + QuoteName(KEY_COLUMN_USAGE.TABLE_NAME)), 
												  KEY_COLUMN_USAGE.COLUMN_NAME, 'IsIdentity'), 0) 
    ELSE
		1
    END AS IS_IDENTITY, 
    (SELECT TOP 1 INFORMATION_SCHEMA.TABLE_CONSTRAINTS.CONSTRAINT_TYPE 
     FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
     INNER JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE ON INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE.TABLE_NAME = INFORMATION_SCHEMA.TABLE_CONSTRAINTS.TABLE_NAME 
     AND INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE.CONSTRAINT_NAME = INFORMATION_SCHEMA.TABLE_CONSTRAINTS.CONSTRAINT_NAME 
     WHERE INFORMATION_SCHEMA.TABLE_CONSTRAINTS.TABLE_NAME = INFORMATION_SCHEMA.COLUMNS.TABLE_NAME 
     AND INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE.COLUMN_NAME = INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME
     AND INFORMATION_SCHEMA.TABLE_CONSTRAINTS.CONSTRAINT_TYPE IN ('PRIMARY KEY', 'FOREIGN KEY')) AS CONSTRAINT_TYPE 
FROM 
    INFORMATION_SCHEMA.COLUMNS 
LEFT JOIN 
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE ON INFORMATION_SCHEMA.KEY_COLUMN_USAGE.TABLE_NAME = INFORMATION_SCHEMA.COLUMNS.TABLE_NAME 
    AND 
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE.COLUMN_NAME = INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME 
LEFT JOIN 
	SYS.IDENTITY_COLUMNS ON SYS.IDENTITY_COLUMNS.NAME = INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME
WHERE 
    INFORMATION_SCHEMA.COLUMNS.TABLE_NAME = '@TABLE_NAME' 
ORDER BY 
    INFORMATION_SCHEMA.COLUMNS.ORDINAL_POSITION
