SELECT DISTINCT 
    INFORMATION_SCHEMA.TABLES.TABLE_NAME                AS TABLE_NAME,
    INFORMATION_SCHEMA.TABLES.TABLE_TYPE                AS TABLE_TYPE,
    INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME              AS COLUMN_NAME, 
    INFORMATION_SCHEMA.COLUMNS.DATA_TYPE                AS DATA_TYPE, 
    INFORMATION_SCHEMA.COLUMNS.ORDINAL_POSITION         AS ORDINAL_POSITION, 
    INFORMATION_SCHEMA.COLUMNS.CHARACTER_MAXIMUM_LENGTH AS CHARACTER_MAXIMUM_LENGTH, 
    INFORMATION_SCHEMA.COLUMNS.NUMERIC_PRECISION        AS NUMERIC_PRECISION, 
    INFORMATION_SCHEMA.COLUMNS.NUMERIC_SCALE            AS NUMERIC_SCALE, 
    INFORMATION_SCHEMA.COLUMNS.IS_NULLABLE              AS IS_NULLABLE, 
    CASE WHEN 
		ISNULL(ColumnProperty(Object_ID(QuoteName(KEY_COLUMN_USAGE.TABLE_SCHEMA) + '.' + QuoteName(KEY_COLUMN_USAGE.TABLE_NAME)), 
												  KEY_COLUMN_USAGE.COLUMN_NAME, 'IsIdentity'), 0) = 1 THEN 
		1
	ELSE 
		(SELECT TOP 1 
			C.IS_IDENTITY 
		 FROM 
			SYS.OBJECTS O 
		 INNER JOIN 
			SYS.COLUMNS C ON O.OBJECT_ID = C.OBJECT_ID 
		 WHERE 
			O.TYPE = 'U' 
		 AND 
			O.NAME = INFORMATION_SCHEMA.COLUMNS.TABLE_NAME
		AND
			C.NAME = INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME)
	END 
                                                        AS IS_IDENTITY, 
    (SELECT TOP 1 INFORMATION_SCHEMA.TABLE_CONSTRAINTS.CONSTRAINT_TYPE 
     FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
     INNER JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE ON INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE.TABLE_NAME = INFORMATION_SCHEMA.TABLE_CONSTRAINTS.TABLE_NAME 
     AND INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE.CONSTRAINT_NAME = INFORMATION_SCHEMA.TABLE_CONSTRAINTS.CONSTRAINT_NAME 
     WHERE INFORMATION_SCHEMA.TABLE_CONSTRAINTS.TABLE_NAME = INFORMATION_SCHEMA.COLUMNS.TABLE_NAME 
     AND INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE.COLUMN_NAME = INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME
     AND INFORMATION_SCHEMA.TABLE_CONSTRAINTS.CONSTRAINT_TYPE IN ('PRIMARY KEY', 'FOREIGN KEY')) 
                                                        AS CONSTRAINT_TYPE 
FROM 
    INFORMATION_SCHEMA.TABLES 
LEFT JOIN 
    INFORMATION_SCHEMA.COLUMNS ON INFORMATION_SCHEMA.COLUMNS.TABLE_NAME = INFORMATION_SCHEMA.TABLES.TABLE_NAME
LEFT JOIN 
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE ON INFORMATION_SCHEMA.KEY_COLUMN_USAGE.TABLE_NAME = INFORMATION_SCHEMA.COLUMNS.TABLE_NAME 
    AND 
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE.COLUMN_NAME = INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME 
WHERE 
    INFORMATION_SCHEMA.TABLES.TABLE_NAME <> 'sysdiagrams' 
AND 
    INFORMATION_SCHEMA.TABLES.TABLE_NAME <> 'sysmessages' 
AND 
    INFORMATION_SCHEMA.TABLES.TABLE_NAME <> 'sysobjects' 
ORDER BY 
    INFORMATION_SCHEMA.TABLES.TABLE_NAME, 
    INFORMATION_SCHEMA.COLUMNS.ORDINAL_POSITION
